cooperative/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from main import views as main 
from user import views as user
from customer import views as customer

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("", customer.AddEntryView.as_view(), name="add-entry"),
    
    path("overview/", main.HomeView.as_view(), name="overview"),
    path("get-customer-name/", customer.AjaxReturnCustomerID.as_view(), name="get-customer-name"),
    path("customer/<int:pk>/", customer.CustomerDetailView.as_view(), name="customer"),
    path("add-customer/", customer.CustomerCreateView.as_view(), name="add-customer"),
    path("customers/", customer.CustomerListView.as_view(), name="customers"),
    path("entries/", customer.EntryListView.as_view(), name="entries"),
    
    path("users/", user.UserListView.as_view(), name="users"),
    path("add-user/", user.UserCreateView.as_view(), name="add-user"),
    path("today/", user.UserEntriesTodayView.as_view(), name="entries-today"),
    path("summaries/", user.DailySummaryView.as_view(), name="summaries"),
    
    path("login/", user.LoginView.as_view(), name="login"),
    path("logout/", user.LogoutView.as_view(), name="logout")
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from autoslug import AutoSlugField
from customer.utils import generate_filename
from django.urls import reverse


class Customer(models.Model):
    
    def image_location(self, filename):
        file_format = filename.split('.')[1]
        filename = generate_filename() + '.' + file_format
        return '/'.join(['customer/passports/', self.name, filename])
    
    name = models.CharField(max_length=50, null=False, blank=False)
    date_added = models.DateTimeField(auto_now_add=True)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    passport = models.ImageField(upload_to=image_location, default='/defaults/profile-picture.png')
    email =  models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=False, unique=True)
    address = models.TextField(null=True, blank=True)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('customer', kwargs={"pk": self.id})
    
    
class Deposit(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_saved = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0, help_text="Customer's account balance after deposit entry")
    is_deposit = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.amount} for {self.customer}"
    
    
class Withdrawal(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_saved = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0, help_text="Customer's account balance after deposit entry")
    is_withdrawal = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.amount} for {self.customer}"
    
    
class DailySummary(models.Model):
    date = models.DateField(null=True, blank=False, unique=True)
    total_deposit = models.IntegerField(default=0)
    total_withdrawal = models.IntegerField(default=0)
    no_of_deposits = models.IntegerField(default=0)
    no_of_withdrawals = models.IntegerField(default=0)
    
    def __str__(self):
        return self.date
    
    def reset(self):
        self.total_deposit = 0
        self.total_withdrawal = 0
        self.no_of_deposits = 0
        self.no_of_withdrawals = 0
        return self.save()

main/models.py
from django.db import models

# Create your models here.

customer/forms.py
from django import forms
from user.forms import MyBaseForm, MyBaseModelForm
from customer.models import Deposit, Withdrawal, Customer
from django.forms import ValidationError


class EntryForm(MyBaseForm):
    entry_type = forms.ChoiceField(choices=[(1, 'DEPOSIT'), (2, "WITHDRAWAL")], required=True)
    customer_id = forms.CharField(required=True)
    amount = forms.IntegerField(required=True, min_value=1)

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        customer = Customer.objects.get(id=self.cleaned_data["customer_id"])
        if self.cleaned_data["entry_type"] == "2" and amount > customer.balance:
            raise ValidationError(f"Available balance is {customer.balance}")
        return amount

    def save(self, user):
        customer = Customer.objects.get(id=self.cleaned_data["customer_id"])
        amount = self.cleaned_data['amount']
        entry_type = self.cleaned_data["entry_type"]
        if entry_type == "1":
            Deposit.objects.create(
                customer=customer,
                user=user,
                amount=amount,
                balance=customer.balance + amount
            )
        if entry_type == "2": 
            Withdrawal.objects.create(
                customer=customer,
                user=user,
                amount=amount,
                balance=customer.balance - amount
            )
        return customer
    

class CustomerCreateForm(MyBaseModelForm):
    class Meta:
        model = Customer 
        fields = ("name", "email", "phone", "address", "passport")

customer/views.py
from django.views.generic.edit import FormView, CreateView
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http.response import JsonResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from customer.forms import EntryForm, CustomerCreateForm
from customer.models import Customer, Deposit, Withdrawal
from itertools import chain
from django.contrib.auth.mixins import LoginRequiredMixin
from user.mixins import StaffRequiredMixin


class AddEntryView(LoginRequiredMixin, FormView):
    template_name = 'customer/add_entry.html'
    form_class = EntryForm
    success_url = reverse_lazy('entries-today')
    
    def form_valid(self, form):
        form.save(self.request.user)
        return HttpResponseRedirect(self.get_success_url())
    

class AjaxReturnCustomerID(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        customer_id = request.GET.get("customer_id", 0)
        data = {'ok': True}
        try:
            customer = Customer.objects.get(id=int(customer_id))
            data['name'] = customer.name
        except Customer.DoesNotExist:
            data['ok'] = False
        return JsonResponse(data=data)
    
    
    
class CustomerCreateView(LoginRequiredMixin, CreateView):
    template_name = "customer/add_customer.html"
    model = Customer 
    form_class = CustomerCreateForm
    success_url = reverse_lazy("customers")
    
    def form_valid(self, form):
        customer = form.save()
        customer.user = self.request.user
        customer.save()
        return HttpResponseRedirect(self.success_url)
    
    
class CustomerDetailView(StaffRequiredMixin, DetailView):
    template_name = "customer/customer.html"
    model = Customer 
    context_object_name = "customer"
    query_pk_and_slug = True
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        entries = sorted(chain(list(self.object.deposit_set.all()), list(self.object.withdrawal_set.all())), key=lambda instance: instance.date_created) 
        context["entries"] = entries
        total_deposit = 0
        for deposit in self.object.deposit_set.all():
            total_deposit += deposit.amount
        context['total_deposit'] = total_deposit
        total_withdrawal = 0
        for withdrawal in self.object.withdrawal_set.all():
            total_withdrawal += withdrawal.amount
        context['total_withdrawal'] = total_withdrawal
        self.object.balance = total_deposit - total_withdrawal
        self.object.save()
        return context
    
    
    
class CustomerListView(LoginRequiredMixin, ListView):
    template_name = "customer/customers.html"
    model = Customer
    context_object_name = "customers"
    ordering = ["name", "balance"]
    

class EntryListView(StaffRequiredMixin, ListView):
    template_name = "customer/entries.html"
    model = Deposit 
    context_object_name = "entries"
    
    def get_queryset(self):
        entries = sorted(chain(list(Deposit.objects.all()), list(Withdrawal.objects.all())), key=lambda instance: instance.date_created, reverse=True) 
        return entries

main/views.py
from django.views.generic import TemplateView 
from customer.models import Customer
from django.views.generic.list import ListView
from user.mixins import StaffRequiredMixin


class HomeView(StaffRequiredMixin, ListView):
    template_name = "main/overview.html"
    model = Customer
    context_object_name = "customers"
    ordering = ["name", "balance",]

main/templates/customer/add_customer.html
{% extends "main/base.html" %} {% load static %} {% load widget_tweaks %} {% block main_content %} 
    <div class="card w-500 mw-full m-auto">
        <h2 class="card-title"> Add Customer </h2>
        <form method="POST"
            class=""> {% csrf_token %} 
            {% for field in form %}
            <div class="form-group">
                <label for="entry_type"
                    class="required">{{ field.label_tag }}</label>
                {% render_field field class+="form-control" %}
                {{ field.errors }} 
            </div>
            {% endfor %}
            <input class="btn btn-primary btn-block submit-btn" type="submit" value="Submit" >
        </form>
    </div>
{% endblock main_content %}

{% block js %}

{% endblock js %}

main/templates/customer/add_entry.html
{% extends "main/base.html" %} {% load static %} {% load widget_tweaks %} {% block main_content %} 
    <div class="card w-500 mw-full m-auto">
        <h2 class="card-title"> Add Entry </h2>
        <form method="POST"
            class=""> {% csrf_token %} <div class="form-group">
                <label for="entry_type"
                    class="required">Entry Type</label>
                {% render_field form.entry_type class+="form-control" placeholder="choose one" %}
                {{ form.entry_type.errors }} 
            </div>
            <div class="form-group">
                <label for="customer_id"
                    class="required">Customer ID</label>
                {% render_field form.customer_id class+="form-control" placeholder="Customer ID" %}
                {{ form.customer_id.errors }} 
            </div>
            <div class="form-group">
                <label for="customer_name"
                    class="required">Customer Name</label>
                <input type="text" name="customer_name" class="form-control customer_name" required disabled>
            </div>
            <div class="form-group">
                <label for="amount"
                    class="required">Amount</label>
                {% render_field form.amount class+="form-control" placeholder="Amount" %}
                {{ form.amount.errors }} 
            </div>
            <input class="btn btn-primary btn-block submit-btn" type="submit" value="Submit" disabled >
        </form>
    </div>
{% endblock main_content %}

{% block js %}
<script>
function getCustomerName() {
    if ($("#id_customer_id").val() != "") {
        console.log('sent')
        $.ajax({
            url: "{% url 'get-customer-name' %}",
            data: {
                'customer_id': $("#id_customer_id").val()
            },
            success: function (data) {
                console.log(data)
                if (data["ok"]) {
                    $(".customer_name").val(data["name"]);
                    $('.submit-btn').prop('disabled', false);
                } else {
                    $(".customer_name").val("");
                    $('.submit-btn').prop('disabled', true);
                }
            }
        });
    } else { 
        $(".customer_name").val(""); 
        $('.submit-btn').prop('disabled', true);
    }
}
getCustomerName();
    $("#id_customer_id").keyup(function () {
        getCustomerName();
    });
</script>
{% endblock js %}

main/templates/customer/customer.html
{% extends "main/base.html" %} {% load static %}
 {% block main_content %} 
<div class="row">
<div class="col-md-8">
<div class="table-responsive">
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>{{ customer.name }}</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>Customer ID</td><td>{{ customer.id }}</td></tr>
    <tr><td>Balance</td><td>{{ customer.balance }}</td></tr>
    <tr><td>Total Deposits</td><td>{{ total_deposit }}</td></tr>
    <tr><td>Total withdrawals</td><td>{{ total_withdrawal }}</td></tr>
  </tbody>
</table>
</div>
</div>
<div class="col-md-4 d-flex justify-content-center align-content-center">
<img src="{{ customer.passport.url }}" class="img-fluid rounded-circle w-250 p-10" alt="passport">
</div>
</div>
<div class="mt-20">
<div class="table-responsive">
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>Date</th>
      <th>Deposit</th>
      <th>Withdrawal</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for entry in entries %}
    {% if entry.is_deposit %}
    <tr>
      <td>{{ entry.date_created }}</td>
      <td>{{ entry.amount }}</td>
      <td>-</td>
      <td>{{ entry.balance }}</td>
    </tr>
    {% endif %}
    {% if entry.is_withdrawal %}
    <tr>
      <td>{{ entry.date_created }}</td>
      <td>-</td>
      <td>{{ entry.amount }}</td>
      <td>{{ entry.balance }}</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
</div>
</div>
{% endblock main_content %}

{% block js %}

{% endblock js %}

main/templates/customer/customers.html
{% extends "main/base.html" %} {% load static %}
 {% block main_content %} 
{% if customers %}
<div class="table-responsive">
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>S/N</th>
      <th>Customer Name</th>
        {% if user.is_staff %}
      <th>Added by</th>
        {% endif %}
      <th>ID</th>
      <th>Date Added</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Passport</th>
    </tr>
  </thead>
  <tbody>
    {% for customer in customers %}
    <tr>
      <td>{{ forloop.counter }}</td>
        {% if user.is_staff %}
      <td><a href="{{ customer.get_absolute_url }}">{{ customer.name }}</a></td>
      <td>{{ customer.user.name }}</td>
        {% else %}
      <td>{{ customer.name }}</td>
        {% endif %}
      <td>{{ customer.id }}</td>
      <td>{{ customer.date_added }}</td>
      <td>{{ customer.phone }}</td>
      <td>{{ customer.address }}</td>
      <td><img src="{{ customer.passport.url }}" class="img" alt="" width="200" height="150"></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<p>No customers yet</p>
{% endif %}
{% endblock main_content %}

{% block js %}

{% endblock js %}

main/templates/customer/entries.html
{% extends "main/base.html" %} {% load static %}
 {% block main_content %} 
{% if entries %}
<div class="table-responsive">
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>S/N</th>
      <th>Customer Name</th>
      <th>ID</th>
      <th>Date Created</th>
      <th>Amount</th>
      <th>Entry Type</th>
      <th>Entered By</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for entry in entries %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ entry.customer.name }}</td>
      <td>{{ entry.id }}</td>
      <td>{{ entry.date_created }}</td>
      <td>{{ entry.amount }}</td>
      <td>{% if entry.is_deposit %}DEPOSIT{% else %}WITHDRAWAL{% endif %}</td>
      <td>{{ entry.user }}</td>
      <td>{{ entry.balance }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<p>No entries yet</p>
{% endif %}
{% endblock main_content %}

{% block js %}

{% endblock js %}

main/templates/customer/withdrawals.html
{% extends "main/base.html" %} {% load static %}
 {% block main_content %} 
{% if withdrawals %}
<div class="table-responsive">
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>S/N</th>
      <th>ID</th>
      <th>Customer Name</th>
      <th>Date Created</th>
      <th>Amount</th>
      <th>User</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for withdrawal in withdrawals %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ withdrawal.id }}</td>
      <td>{{ withdrawal.customer }}</td>
      <td>{{ withdrawal.date_created }}</td>
      <td>{{ withdrawal.amount }}</td>
      <td>{{ withdrawal.user }}</td>
      <td>{{ withdrawal.balance }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<p>No withdrawals yet</p>
{% endif %}
{% endblock main_content %}

{% block js %}

{% endblock js %}