cooperative/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from main import views as main 
from user import views as user
from customer import views as customer

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("", customer.AddEntryView.as_view(), name="add-entry"),
    
    path("overview/", main.HomeView.as_view(), name="overview"),
    path("get-customer-name/", customer.AjaxReturnCustomerID.as_view(), name="get-customer-name"),
    path("customer/<int:pk>/", customer.CustomerDetailView.as_view(), name="customer"),
    path("add-customer/", customer.CustomerCreateView.as_view(), name="add-customer"),
    path("customers/", customer.CustomerListView.as_view(), name="customers"),
    path("entries/", customer.EntryListView.as_view(), name="entries"),
    
    path("users/", user.UserListView.as_view(), name="users"),
    path("add-user/", user.UserCreateView.as_view(), name="add-user"),
    path("today/", user.UserEntriesTodayView.as_view(), name="entries-today"),
    path("summaries/", user.DailySummaryView.as_view(), name="summaries"),
    
    path("login/", user.LoginView.as_view(), name="login"),
    path("logout/", user.LogoutView.as_view(), name="logout")
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from autoslug import AutoSlugField
from customer.utils import generate_filename
from django.urls import reverse


class Customer(models.Model):
    
    def image_location(self, filename):
        file_format = filename.split('.')[1]
        filename = generate_filename() + '.' + file_format
        return '/'.join(['customer/passports/', self.name, filename])
    
    name = models.CharField(max_length=50, null=False, blank=False)
    date_added = models.DateTimeField(auto_now_add=True)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    passport = models.ImageField(upload_to=image_location, default='/defaults/profile-picture.png')
    email =  models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=False, unique=True)
    address = models.TextField(null=True, blank=True)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('customer', kwargs={"pk": self.id})
    
    
class Deposit(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_saved = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0, help_text="Customer's account balance after deposit entry")
    is_deposit = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.amount} for {self.customer}"
    
    
class Withdrawal(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey("user.User", null=True, blank=False, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_saved = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0, help_text="Customer's account balance after deposit entry")
    is_withdrawal = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.amount} for {self.customer}"
    
    
class DailySummary(models.Model):
    date = models.DateField(null=True, blank=False, unique=True)
    total_deposit = models.IntegerField(default=0)
    total_withdrawal = models.IntegerField(default=0)
    no_of_deposits = models.IntegerField(default=0)
    no_of_withdrawals = models.IntegerField(default=0)
    
    def __str__(self):
        return self.date
    
    def reset(self):
        self.total_deposit = 0
        self.total_withdrawal = 0
        self.no_of_deposits = 0
        self.no_of_withdrawals = 0
        return self.save()

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views.generic import TemplateView 
from customer.models import Customer
from django.views.generic.list import ListView
from user.mixins import StaffRequiredMixin


class HomeView(StaffRequiredMixin, ListView):
    template_name = "main/overview.html"
    model = Customer
    context_object_name = "customers"
    ordering = ["name", "balance",]

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible"
        content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        name="viewport" />
    <meta name="viewport"
        content="width=device-width" />
    <!-- Fontawesome icons -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0="
        crossorigin="anonymous">
    <title>Cooperative</title>
    <!-- Halfmoon CSS -->
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon.min.css"
        rel="stylesheet" />
    <link href="{% static 'main/static/css/styles.css' %}"
        rel="stylesheet" />
</head>

<body data-dm-shortcut-enabled="true"
    data-sidebar-shortcut-enabled="true"
    data-set-preferred-mode-onload="true">
    <!-- Modals go here -->
    <!-- Reference: https://www.gethalfmoon.com/docs/modal -->
    <!-- Page wrapper start -->
    <div class="page-wrapper with-navbar with-sidebar"
        data-sidebar-type="full-height overlayed-sm-and-down">
        <!-- logout form -->
        <form action="{% url 'logout' %}"
            class="d-none logout-form"
            method="POST"> {% csrf_token %} </form>
        <div class="sticky-alerts"></div>
        <!-- Navbar start -->
        <nav class="navbar justify-content-between">
            <!-- justify-content-between = justify-content: space-between -->
            <!-- Navbar content with menu button -->
            <div class="navbar-content">
                <!-- Toggle sidebar -->
                <button class="btn"
                    type="button"
                    onclick="halfmoon.toggleSidebar()">
                    <i class="fa fa-bars"
                        aria-hidden="true"></i></button>
            </div>
            <!-- Navbar brand -->
            <a href=""
                class="navbar-brand">
            </a>
            <!-- Navbar content with sign up button -->
            <div class="navbar-content ml-auto">
                <button class="btn btn-square mr-5"
                    type="button"
                    onclick="halfmoon.toggleDarkMode()">
                    <i class="fa fa-moon-o"
                        aria-hidden="true"></i>
                    <span class="sr-only">Toggle dark mode</span> <!-- sr-only = only for screen readers -->
                </button> {% if user.is_authenticated %} <button class="btn btn-primary logout-btn"
                    onclick="logout()"
                    type="button">Sign out</button> {% else %} <button class="btn btn-primary"
                    type="button"><a href="{% url 'login' %}"
                        class="text-white">Sign in</a></button> {% endif %} </div>
        </nav>
        <!-- Navbar end -->
        <!-- Sidebar overlay -->
        <div class="sidebar-overlay"
            onclick="halfmoon.toggleSidebar()"></div>
        <!-- Sidebar start -->
        <div class="sidebar">
            <div class="sidebar-menu">
                <!-- Sidebar brand -->
                <a href="/"
                    class="sidebar-brand mb-20"> COOPERATIVE </a>
                <!-- Sidebar links and titles -->
                <h5 class="sidebar-title">General</h5>
                <div class="sidebar-divider"></div>
                <a href="{% url 'add-entry' %}"
                    class="sidebar-link add-entry">Add Entry</a>
                <a href="{% url 'add-customer' %}"
                    class="sidebar-link add-customer">Add Customer</a>
                <a href="{% url 'entries-today' %}"
                    class="sidebar-link entries-today">Entries Today</a>
                <a href="{% url 'customers' %}"
                    class="sidebar-link customers">Customers</a>
                <br /> {% if user.is_staff %} <h5 class="sidebar-title">Admin Only</h5>
                <div class="sidebar-divider"></div>
                <a href="{% url 'overview' %}"
                    class="sidebar-link overview">Overview</a>
                <a href="{% url 'entries' %}"
                    class="sidebar-link entries">Entries</a>
                <a href="{% url 'summaries' %}"
                    class="sidebar-link summaries">Summaries</a>
                <a href="{% url 'users' %}"
                    class="sidebar-link users">Users</a>
                <a href="{% url 'add-user' %}"
                    class="sidebar-link add-user">Add User</a> {% endif %}
            </div>
        </div>
        <!-- Sidebar end -->
        <!-- Content wrapper start -->
        <div class="content-wrapper">
            <div class="d-flex justify-content-center align-content-center flex-column p-20">
                {% block main_content %}{% endblock main_content %} </div>
        </div>
        <!-- Content wrapper end -->
    </div>
    <!-- Page wrapper end -->
    <!-- Halfmoon JS -->
    <script src="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/js/halfmoon.min.js"></script>
    <script crossorigin="anonymous"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script>
        // logout
        $('.logout-btn').on('click', function () {
            $('form.logout-form').submit();
        });
        $('.sidebar-link a').removeClass("active");
        switch (window.location.pathname) {
            case "{% url 'overview' %}":
                $('.sidebar-link.overview').addClass("active");
                break;
            case "{% url 'add-entry' %}":
                $('.sidebar-link.add-entry').addClass("active");
                break;
            case "{% url 'add-customer' %}":
                $('.sidebar-link.add-customer').addClass("active");
                break;
            case "{% url 'entries-today' %}":
                $('.sidebar-link.entries-today').addClass("active");
                break;
            case "{% url 'customers' %}":
                $('.sidebar-link.customers').addClass("active");
                break;
            case "{% url 'entries' %}":
                $('.sidebar-link.entries').addClass("active");
                break;
            case "{% url 'summaries' %}":
                $('.sidebar-link.summaries').addClass("active");
                break;
            case "{% url 'users' %}":
                $('.sidebar-link.users').addClass("active");
                break;
            case "{% url 'add-user' %}":
                $('.sidebar-link.add-user').addClass("active");
                break;
        }
    </script> {% block js %}{% endblock js %}
</body>

</html>

main/templates/main/overview.html
{% extends "main/base.html" %} {% load static %}
 {% block main_content %} 
{% if customers %}
<table class="table table-bordered m-20">
  <thead>
    <tr>
      <th>S/N</th>
      <th>Customer Name</th>
      <th>ID</th>
      <th>Current Balance</th>
      <th>Total Deposits</th>
      <th>Total withdrawals</th>
      <th>View</th>
    </tr>
  </thead>
  <tbody>
    {% for customer in customers %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ customer.name }}</td>
      <td>{{ customer.id }}</td>
      <td>{{ customer.balance }}</td>
      <td>{{ customer.deposit_set.count }}</td>
      <td>{{ customer.withdrawal_set.count }}</td>
      <td><a href="{{ customer.get_absolute_url }}">View</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No customers yet</p>
{% endif %}
{% endblock main_content %}

{% block js %}

{% endblock js %}